//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xbox360WirelessChatpad.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q W E R T Y")]
        public string ctrl1KeyboardType {
            get {
                return ((string)(this["ctrl1KeyboardType"]));
            }
            set {
                this["ctrl1KeyboardType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl1DeadzoneL {
            get {
                return ((int)(this["ctrl1DeadzoneL"]));
            }
            set {
                this["ctrl1DeadzoneL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl1DeadzoneR {
            get {
                return ((int)(this["ctrl1DeadzoneR"]));
            }
            set {
                this["ctrl1DeadzoneR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ctrl1TriggerAsButton {
            get {
                return ((bool)(this["ctrl1TriggerAsButton"]));
            }
            set {
                this["ctrl1TriggerAsButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ctrl1MouseMode {
            get {
                return ((bool)(this["ctrl1MouseMode"]));
            }
            set {
                this["ctrl1MouseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q W E R T Y")]
        public string ctrl2KeyboardType {
            get {
                return ((string)(this["ctrl2KeyboardType"]));
            }
            set {
                this["ctrl2KeyboardType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl2DeadzoneL {
            get {
                return ((int)(this["ctrl2DeadzoneL"]));
            }
            set {
                this["ctrl2DeadzoneL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl2DeadzoneR {
            get {
                return ((int)(this["ctrl2DeadzoneR"]));
            }
            set {
                this["ctrl2DeadzoneR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ctrl2TriggerAsButton {
            get {
                return ((bool)(this["ctrl2TriggerAsButton"]));
            }
            set {
                this["ctrl2TriggerAsButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ctrl2MouseMode {
            get {
                return ((bool)(this["ctrl2MouseMode"]));
            }
            set {
                this["ctrl2MouseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q W E R T Y")]
        public string ctrl3KeyboardType {
            get {
                return ((string)(this["ctrl3KeyboardType"]));
            }
            set {
                this["ctrl3KeyboardType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl3DeadzoneL {
            get {
                return ((int)(this["ctrl3DeadzoneL"]));
            }
            set {
                this["ctrl3DeadzoneL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl3DeadzoneR {
            get {
                return ((int)(this["ctrl3DeadzoneR"]));
            }
            set {
                this["ctrl3DeadzoneR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ctrl3TriggerAsButton {
            get {
                return ((bool)(this["ctrl3TriggerAsButton"]));
            }
            set {
                this["ctrl3TriggerAsButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ctrl3MouseMode {
            get {
                return ((bool)(this["ctrl3MouseMode"]));
            }
            set {
                this["ctrl3MouseMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q W E R T Y")]
        public string ctrl4KeyboardType {
            get {
                return ((string)(this["ctrl4KeyboardType"]));
            }
            set {
                this["ctrl4KeyboardType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl4DeadzoneL {
            get {
                return ((int)(this["ctrl4DeadzoneL"]));
            }
            set {
                this["ctrl4DeadzoneL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int ctrl4DeadzoneR {
            get {
                return ((int)(this["ctrl4DeadzoneR"]));
            }
            set {
                this["ctrl4DeadzoneR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ctrl4TriggerAsButton {
            get {
                return ((bool)(this["ctrl4TriggerAsButton"]));
            }
            set {
                this["ctrl4TriggerAsButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ctrl4MouseMode {
            get {
                return ((bool)(this["ctrl4MouseMode"]));
            }
            set {
                this["ctrl4MouseMode"] = value;
            }
        }
    }
}
